apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-toolbox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-toolbox
    spec:
      containers:
      - image: mtinny/nginx
        imagePullPolicy: Always
        name: nginx-toolbox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
